accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

contact/urls.py
from django.urls import include, path

from . import views

app_name='contact'

urlpatterns = [
    path('',views.send_message , name='contact'),
]

job/urls.py
from django.urls import path
from .views import job_list, job_details, home, add_job, upload_resume

from . import api


 

app_name = 'job'

urlpatterns = [

    path('', home, name='index'),
    path('jobs/', job_list, name='home'),
    path('upload_resume/', upload_resume, name='upload_resume'),
    path('add_job', add_job, name='add_job'),
    path('<slug:slug>', job_details, name='job_details'),



    path('api/jobs',api.JobApi.as_view() , name='job_list_api'),

    
    

]

src/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('job.urls', namespace='jobs')),
    path('contact-us/', include('contact.urls',namespace='contact')),

    path('api-auth/', include('rest_framework.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from accounts.models import City
from django.urls import reverse
import uuid
from .utils import generate_unique_slug




class City_Job(models.Model):
    city = models.CharField(max_length=50)
    

    class Meta:
        verbose_name = ("City")
        verbose_name_plural = ("Job City")

    def __str__(self):
        return self.city

JOB_TYPE = (
    ('full-time', 'full-time'),
    ('part-time', 'part-time'),
)







class Job(models.Model):

    title           = models.CharField(max_length=100)
    job_type        = models.CharField(max_length=100, choices= JOB_TYPE)
    description     = models.TextField(max_length=1000)
    published_at    = models.DateTimeField(auto_now=True)
    categories      = models.ForeignKey('Category', verbose_name=("Category"), on_delete=models.CASCADE, null=True)
    vacancy         = models.IntegerField(default=1)
    salary          = models.IntegerField(default=0)
    experience      = models.IntegerField(default=1)
    city            = models.ForeignKey(City_Job, on_delete=models.CASCADE, null=True)
    slug            = models.SlugField(blank=True, null=True, unique=True)

    class Meta:
        ordering = ['-published_at']


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug:  # edit
            if slugify(self.title) != self.slug:
                self.slug = generate_unique_slug(Job, self.title)
        else:  # create
            self.slug = generate_unique_slug(Job, self.title)
        super(Job, self).save(*args, **kwargs)




class Category(models.Model):
    cat_name = models.CharField(max_length=250, null=True)
    cat_job = models.ForeignKey(Job, on_delete=models.CASCADE, null=True, blank=True)
    

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    def __str__(self):
        return self.cat_name
        

class Candidate(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    job             = models.ForeignKey(Job, related_name='Apply_job', on_delete=models.CASCADE)
    name            = models.CharField(max_length=100)
    email           = models.EmailField()
    url             = models.URLField()
    cv              = models.FileField(upload_to="Apply/")
    cover_letter    = models.TextField(max_length=1000)
    description     = models.TextField(max_length=1000, null=True)
    created         = models.DateTimeField(auto_now=True)
    job_name        = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.name



class Employee(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    url = models.URLField()
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    




class Resume(models.Model):
    candidate = models.ForeignKey(Candidate, related_name='Resume', on_delete=models.CASCADE, blank=True, null=True )
    name = models.CharField(max_length=100)
    email = models.EmailField()
    url = models.URLField()
    cv = models.FileField(upload_to="Apply/")
    cover_letter = models.TextField(max_length=1000)
    created = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name



class Companie(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    url = models.URLField()
    image   = models.ImageField(upload_to='Company/', blank=True, null=True)

    def __str__(self):
        return self.name

job/forms.py
from django import forms

from .models import Candidate, Job, Candidate, Resume, User




class JobForm(forms.ModelForm):
    title               = forms.CharField(max_length=200, widget=forms.TextInput({ "placeholder": ""}))



    class Meta:
        model = Job
        fields = ['title', 'description', 'job_type', 'vacancy','salary', 'experience', 'city']


class ResumeForm(forms.ModelForm):
    name          = forms.CharField(max_length=200, widget=forms.TextInput({"placeholder": ""}))
    email         = forms.EmailField(max_length=200, widget=forms.TextInput({ "placeholder": ""}))
    url           = forms.URLField(required=False, widget=forms.TextInput({ "placeholder": ""}))

    class Meta:
        model = Resume

        fields = ['name', 'email', 'url', 'cv', 'cover_letter']




class JobSearchForm(forms.Form):
    search_text =  forms.CharField(
                    required = False,
                    label='Search Job!',
                    widget=forms.TextInput(attrs={'placeholder': 'search here!'})
                  )

    

job/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render
from django.views.generic import ListView,  DetailView, TemplateView
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import *
from .forms import JobForm, ResumeForm, JobSearchForm
from django.contrib import messages
from django.db.models import Q
from .filters import JobFilter
from django.shortcuts import get_object_or_404
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned





def home(request):
    jobs = Job.objects.all()
    companies = Companie.objects.all()
    candidates = Candidate.objects.all()
    caregories = Category.objects.all()
    

    context = {
        'jobs': jobs,
        'companies': companies,
        'candidates': candidates,
        'caregories': caregories,
        
    }
    return render(request, 'job/index.html', context)





def job_list(request):
    job_list = Job.objects.all()
    my_filter = JobFilter(request.GET, queryset=job_list)
    job_list = my_filter.qs

    paginator = Paginator(job_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'jobs': page_obj, 
        'list': job_list,
        'my_filter': my_filter 
    }
    return render(request, 'job/jobs.html', context)


def job_details(request, slug):
    job_list = Job.objects.get(slug=slug)
    if request.method == 'POST':
        form = ResumeForm(request.POST, request.FILES)
        if form.is_valid():
            my_form = form.save(commit=False)
            my_form.job = job_list
            my_form = form.save()
            form = ResumeForm()

            return redirect('/')

    else:
        form = ResumeForm()


    context = {
        'jobs': job_list,
        'form': form
    }
    return render(request, 'job/job_details.html', context)



def add_job(request):

    if request.method == 'POST':
        form = JobForm(request.POST, request.FILES)
        print('done')
        if form.is_valid():
            job_form = form.save(commit=False)
            job_form.job = job_list
            job_form = form.save()
            messages.success(request, "Job Added")

            return redirect('/')
            
    
    else:
        form = JobForm()


    context = {
        'jobs': add_job,
        'form': form
    }
    return render(request, 'job/add_job.html', context)


@login_required
def upload_resume(request):
    resume = Resume.objects.all()
    if request.method == 'POST':
        form = ResumeForm(request.POST, request.FILES)
        if form.is_valid():
            resume_form = form.save(commit=False)
            resume_form.resume = resume
            resume_form = form.save()
            form = ResumeForm()

            return redirect('home')
            
    
    else:
        form = ResumeForm()


    context = {
        'resume': upload_resume,
        'form': form
    }
    return render(request, 'job/upload_resume.html', context)

job/templates/job/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>Job Board</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link
      rel="shortcut icon"
      type="image/x-icon"
      href="{% static 'img/favicon.png' %}"
    />
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}" />
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}" />

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/cards.css' %}" />
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
  </head>

  <body>
    <!--[if lte IE 9]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please
        <a href="https://browsehappy.com/">upgrade your browser</a> to improve
        your experience and security.
      </p>
    <![endif]-->

    <!-- header-start -->
    <header>
      <div class="header-area">
        <div id="sticky-header" class="main-header-area">
          <div class="container-fluid">
            <div class="header_bottom_border">
              <div class="row align-items-center">
                <div class="col-xl-3 col-lg-2">
                  <div class="logo">
                    <a href="{% url 'jobs:index' %}">
                      <img src="{% static 'img/logo.png' %}" alt="" />
                    </a>
                  </div>
                </div>
                <div class="col-xl-6 col-lg-7">
                  <div class="main-menu d-none d-lg-block">
                    <nav>
                      <ul id="navigation">
                        <li><a href="{% url 'jobs:index' %}">home</a></li>
                        <li><a href="{% url 'jobs:home' %}">Browse Job</a></li>
                        
                        <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                      </ul>
                    </nav>
                  </div>
                </div>
                <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                  <div class="Appointment">
                    
                    
                    <div class="phone_num d-none d-xl-block">
                      {% if not user.is_authenticated %}
                      <a class="mr-2 font-weight-bold" href="{% url 'login' %}">Log in</a>
                      <a class="boxed-btn3 font-weight-bold" href="{% url 'accounts:signup' %}">Join Us</a>
                      {% endif %}
                    </div>
                    <div class="d-none d-lg-block">
                      {% if user.is_authenticated %}
                      
                      <a class="boxed-btn3 mr-3" href="{% url 'jobs:add_job' %}">Post a Job</a>

                      <a class="text-white" href="{% url 'logout' %}">Log Out</a>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="col-12">
                  <div class="mobile_menu d-block d-lg-none"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <!-- header-end -->

    {% block body %}
    {% endblock %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
          <div class="container">
            <div class="row">
              <div class="col-xl-3 col-md-6 col-lg-3">
                <div
                  class="footer_widget wow fadeInUp"
                  data-wow-duration="1s"
                  data-wow-delay=".3s"
                >
                  <div class="footer_logo">
                    <a href="#">
                      <img src="{% static 'img/logo.png' %}" alt="" />
                    </a>
                  </div>
                  <p>
                    finloan@support.com <br />
                    +10 873 672 6782 <br />
                    600/D, Green road, NewYork
                  </p>
                  <div class="socail_links">
                    <ul>
                      <li>
                        <a href="#">
                          <i class="ti-facebook"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-google-plus"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-twitter"></i>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-instagram"></i>
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-xl-2 col-md-6 col-lg-2">
                <div
                  class="footer_widget wow fadeInUp"
                  data-wow-duration="1.1s"
                  data-wow-delay=".4s"
                >
                  <h3 class="footer_title">
                    Company
                  </h3>
                  <ul>
                    <li><a href="#">About </a></li>
                    <li><a href="#"> Pricing</a></li>
                    <li><a href="#">Carrier Tips</a></li>
                    <li><a href="#">FAQ</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-xl-3 col-md-6 col-lg-3">
                <div
                  class="footer_widget wow fadeInUp"
                  data-wow-duration="1.2s"
                  data-wow-delay=".5s"
                >
                  <h3 class="footer_title">
                    Category
                  </h3>
                  <ul>
                    <li><a href="#">Design & Art</a></li>
                    <li><a href="#">Engineering</a></li>
                    <li><a href="#">Sales & Marketing</a></li>
                    <li><a href="#">Finance</a></li>
                  </ul>
                </div>
              </div>
              <div class="col-xl-4 col-md-6 col-lg-4">
                <div
                  class="footer_widget wow fadeInUp"
                  data-wow-duration="1.3s"
                  data-wow-delay=".6s"
                >
                  <h3 class="footer_title">
                    Subscribe
                  </h3>
                  <form action="#" class="newsletter_form">
                    <input type="text" placeholder="Enter your mail" />
                    <button type="submit">Subscribe</button>
                  </form>
                  <p class="newsletter_text">
                    Esteem spirit temper too say adieus who direct esteem esteems
                    luckily.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          class="copy-right_text wow fadeInUp"
          data-wow-duration="1.4s"
          data-wow-delay=".3s"
        >
          <div class="container">
            <div class="footer_border"></div>
            <div class="row">
              <div class="col-xl-12">
                <p class="copy_right text-center">
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                  Copyright &copy;
                  <script>
                    document.write(new Date().getFullYear());
                  </script>
                  All rights reserved | This template is made with
                  <i class="fa fa-heart-o" aria-hidden="true"></i> by
                  <a href="https://colorlib.com" target="_blank">Colorlib</a>
                  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <!--/ footer end  -->
  
      <!-- link that opens popup -->
      <!-- JS here -->
      <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>
      <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
      <script src="{% static 'js/ajax-form.js' %}"></script>
      <script src="{% static 'js/waypoints.min.js' %}"></script>
      <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
      <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
      <script src="{% static 'js/scrollIt.js' %}"></script>
      <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
      <script src="{% static 'js/wow.min.js' %}"></script>
      <script src="{% static 'js/nice-select.min.js' %}"></script>
      <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
      <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'js/plugins.js' %}"></script>
      <!-- <script src="js/gijgo.min.js' %}"></script> -->
      <script src="{% static 'js/range.js' %}"></script>
  
      <!--contact js-->
      <script src="{% static 'js/contact.js' %}"></script>
      <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
      <script src="{% static 'js/jquery.form.js' %}"></script>
      <script src="{% static 'js/jquery.validate.min.js' %}"></script>
      <script src="{% static 'js/mail-script.js' %}"></script>
  
      <script src="{% static 'js/main.js' %}"></script>
      <script src="{% static 'js/script.js' %}"></script>
  
      <script>
        $(function () {
          $("#slider-range").slider({
            range: true,
            min: 0,
            max: 24600,
            values: [750, 24600],
            slide: function (event, ui) {
              $("#amount").val(
                "$" + ui.values[0] + " - $" + ui.values[1] + "/ Year"
              );
            },
          });
          $("#amount").val(
            "$" +
              $("#slider-range").slider("values", 0) +
              " - $" +
              $("#slider-range").slider("values", 1) +
              "/ Year"
          );
        });
      </script>
    </body>
  </html>
  

job/templates/job/genres.html
{% load mptt_tags %}
<ul>
    {% recursetree genres %}
        <li>
            {{ node.name }}
            {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
            {% endif %}
        </li>
    {% endrecursetree %}
</ul>


<p>{{total}}</p>



    

job/templates/job/index.html
{% extends "job/base.html" %} {% load static %} {% block body %}

<!-- slider_area_start -->
<div class="slider_area">
  <div class="single_slider d-flex align-items-center slider_bg_1">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-7 col-md-6">
          <div class="slider_text">
            <h5
              class="wow fadeInLeft"
              data-wow-duration="1s"
              data-wow-delay=".2s"
            >
              {{jobs.count}}+ Jobs listed
            </h5>
            <h3
              class="wow fadeInLeft"
              data-wow-duration="1s"
              data-wow-delay=".3s"
            >
              Find your Dream Job
            </h3>
            <p
              class="wow fadeInLeft"
              data-wow-duration="1s"
              data-wow-delay=".4s"
            >
              We provide online instant cash loans with quick approval that suit
              your term length
            </p>
            <div
              class="sldier_btn wow fadeInLeft"
              data-wow-duration="1s"
              data-wow-delay=".5s"
            >
              <a href="{% url 'job:upload_resume' %}" class="boxed-btn3"
                >Upload your Resume</a
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div
    class="ilstration_img wow fadeInRight d-none d-lg-block text-right"
    data-wow-duration="1s"
    data-wow-delay=".2s"
  >
    <img src="{% static 'img/banner/unnamed.png' %}" alt="" />
  </div>
</div>
<!-- slider_area_end -->

<!-- catagory_area -->
<div class="catagory_area">
  <div class="container">
    <div class="row cat_search">
      <div class="col-lg-3 col-md-4">
        <div class="single_input">
          <input type="text" placeholder="Search a job" autocomplete="off" />
        </div>
      </div>
      <div class="col-lg-3 col-md-4">
        <div class="single_input">
          <select class="wide">
            <option data-display="Location">Location</option>
            {% for job in jobs %}

            <option value="1">{{ job.city }}</option>

            {% endfor %}
          </select>
        </div>
      </div>
      <div class="col-lg-3 col-md-4">
        <div class="single_input">
          <select class="wide">
            <option data-display="Category">Category</option>
            {% for job in jobs %}

            <option value="1">{{ job.categories }}</option>

            {% endfor %}
          </select>
        </div>
      </div>
      <div class="col-lg-3 col-md-12">
        <div class="job_btn">
          <a href="#" class="boxed-btn3">Find Job</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ catagory_area -->

<!-- job_listing_area_start  -->
<div class="job_listing_area">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="section_title">
          <h3>Recent Jobs</h3>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="brouse_job text-right">
          <a href="{% url 'jobs:home' %}" class="boxed-btn4">Browse More Job</a>
        </div>
      </div>
    </div>
    <div class="job_lists">
      <div class="row">
        {% for job in jobs|slice:"5" %}

        <div class="col-lg-12 col-md-12">
          <div class="single_jobs white-bg d-flex justify-content-between">
            <div class="jobs_left d-flex align-items-center">
              <div class="thumb">
                <img src="{{job.image.url}}" alt="" />
              </div>
              <div class="jobs_conetent">
                <a href="{% url 'jobs:job_details' job.slug %}">
                  <h4>{{job.title}}</h4>
                </a>
                <div class="links_locat d-flex align-items-center">
                  <div class="location">
                    <p><i class="fa fa-map-marker"></i>{{job.city}}</p>
                  </div>
                  <div class="location">
                    <p><i class="fa fa-clock-o"></i> {{job.type}}</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="jobs_right">
              <div class="apply_now">
                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                <a
                  href="{% url 'jobs:job_details' job.slug %}"
                  class="boxed-btn3"
                  >Apply Now</a
                >
              </div>
              <div class="date">
                <p>{{job.published_at}}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
<!-- job_listing_area_end  -->

<!-- featured_candidates_area_start  -->
<div class="popular_catagory_area">
  <div class="container">
    <div class="row"> 
      <div class="col-lg-12">
        <div class="section_title mb-40">
          <h3>Popolar Categories</h3>
        </div>
      </div>
    </div>
    <div class="row">
      {% for category in caregories %}
      <div class="col-lg-4 col-xl-3 col-md-6">
        <div class="single_catagory">
          <a href=""><h4>{{category.cat_name}}</h4></a>

          
        </div>
      </div>
             
      {% endfor %}
    </div>
  </div>
</div>

<!-- Team -->

<!-- featured_candidates_area_end  -->

<div class="top_companies_area">
  <div class="container">
    <div class="row align-items-center mb-40">
      <div class="col-lg-6 col-md-6">
        <div class="section_title">
          <h3>Top Companies</h3>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="brouse_job text-right">
          <a href="{% url 'jobs:home' %}" class="boxed-btn4">Browse More Job</a>
        </div>
      </div>
    </div>
    <div class="row">
      {% for company in companies %}

      <div class="col-lg-4 col-xl-3 col-md-6">
        <div class="single_company">
          <div class="thumb">
            <img src="{{company.image.url}}" alt="" />
          </div>
          <a href="jobs.html">
            <h3>{{company.name}}</h3>
          </a>
          <p><span>50</span> Available position</p>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

<!-- job_searcing_wrap  -->
<div class="job_searcing_wrap overlay">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 offset-lg-1 col-md-6">
        <div class="searching_text">
          <h3>Looking for a Job?</h3>
          <p>We provide online instant cash loans with quick approval</p>
          <a href="{% url 'jobs:home' %}" class="boxed-btn3">Browse Job</a>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1 col-md-6">
        <div class="searching_text">
          <h3>Looking for a Expert?</h3>
          <p>We provide online instant cash loans with quick approval</p>
          <a href="{% url 'jobs:add_job' %}" class="boxed-btn3">Post a Job</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- job_searcing_wrap end  -->

<!-- testimonial_area  -->
<div class="testimonial_area">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="section_title text-center mb-40">
          <h3>Testimonial</h3>
        </div>
      </div>
      <div class="col-xl-12">
        <div class="testmonial_active owl-carousel">
          <div class="single_carousel">
            <div class="row">
              <div class="col-lg-11">
                <div class="single_testmonial d-flex align-items-center">
                  <div class="thumb">
                    <img
                      src="{% static 'img/testmonial/author.png' %}"
                      alt=""
                    />
                    <div class="quote_icon">
                      <i class="Flaticon flaticon-quote"></i>
                    </div>
                  </div>
                  <div class="info">
                    <p>
                      "Working in conjunction with humanitarian aid agencies, we
                      have supported programmes to help alleviate human
                      suffering through animal welfare when people might depend
                      on livestock as their only source of income or food.
                    </p>
                    <span>- Micky Mouse</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="single_carousel">
            <div class="row">
              <div class="col-lg-11">
                <div class="single_testmonial d-flex align-items-center">
                  <div class="thumb">
                    <img
                      src="{% static 'img/testmonial/author.png' %}"
                      alt=""
                    />
                    <div class="quote_icon">
                      <i class="Flaticon flaticon-quote"></i>
                    </div>
                  </div>
                  <div class="info">
                    <p>
                      "Working in conjunction with humanitarian aid agencies, we
                      have supported programmes to help alleviate human
                      suffering through animal welfare when people might depend
                      on livestock as their only source of income or food.
                    </p>
                    <span>- Micky Mouse</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="single_carousel">
            <div class="row">
              <div class="col-lg-11">
                <div class="single_testmonial d-flex align-items-center">
                  <div class="thumb">
                    <img
                      src="{% static 'img/testmonial/author.png' %}"
                      alt=""
                    />
                    <div class="quote_icon">
                      <i class="Flaticon flaticon-quote"></i>
                    </div>
                  </div>
                  <div class="info">
                    <p>
                      "Working in conjunction with humanitarian aid agencies, we
                      have supported programmes to help alleviate human
                      suffering through animal welfare when people might depend
                      on livestock as their only source of income or food.
                    </p>
                    <span>- Micky Mouse</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /testimonial_area  -->

{% endblock %}